config/routes.rb
Tinkerbell::Application.routes.draw do

  resources :locations

  resources :rings

   root :to => 'welcome#index'
   resources :notifications
   resources :apps
   resources :locations do
     collection do
       get :destroy_all
     end
   end

   get "location/last"

   resources :rings do
     collection do
       get :destroy_all
     end
   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @rings=Ring.all()
    @loc=Location.all().reverse!
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
%h1 Welcome
%p  Sistema de timbres
%p= link_to "Para registrar un timbrazo de click aquí", new_ring_path()
%p= link_to "Para registrar una ubicacion de click aquí", new_location_path()
%p= link_to "Para registrar una aplicación de click aqui", new_app_path()
%p= link_to "Para registrar una notificacion de click aqui", new_notification_path()

%table#table
  %thead
    %tr
      %th Nombre
      %th Mensaje
      %th Fecha/hora
      %th
      %th
      %th
  %tbody
    - @rings.each do |ring|
      %tr
        %td= ring.name
        %td= ring.description
        %td= ring.created_at
        %td= link_to "Editar", edit_ring_path(ring)
        %td= link_to "Borrar", ring_path(ring), :method => :delete, :confirm => '¿Esta seguro?'

%table#table
  %thead
    %tr
      %th Nombre
      %th Fecha/hora
      %th Longitud
      %th Latitud
      %th Velocidad
      %th
      %th
      %th
  %tbody
    - @loc.each do |loc|
      %tr
        %td= loc.name
        %td= loc.created_at
        %td= loc.longitude
        %td= loc.latitude
        %td= loc.speed
        %td= link_to "Editar", edit_location_path(loc)
        %td= link_to "Borrar", location_path(loc), :method => :delete, :confirm => '¿Esta seguro?'